### ISSUE TITLE
common_provinces表缺失

### ISSUE THREAD

**Issue by tang86** [jianyan74/rageframe#1]
感觉这个项目特别棒，安装好跑起来，进入个人中心时，页面报错common_provinces表缺失（我自己已经按数据字典创建了这张表，并从网上找了行政区数据）
如果能把这张表补充到数据迁移文件中就太好了，加油

**Comment by jianyan74** [comment]
安装文档有说明哦，可以自行下载，有下载链接的，下个版本会把表直接加入到项目
